---

- hosts: all
  become: true

  vars:
    steam_user:
      name: steam
      home_dir: /home/steam
    server_install_dir: "{{ steam_user.home_dir }}/starbound_server"
    install_script: "{{ server_install_dir }}/install-script.txt"

  vars_prompt:
    - name: steam_username
      prompt: "What is your Steam username?"
      private: no

    - name: steam_password
      prompt: "What is your Steam password?"
      private: yes

    - name: starbound_admin_password
      prompt: "What would you like to set as the Starbound server admin password?"
      private: yes

    - name: steam_mfa_code
      prompt: "What is your Steam 2-factor-auth code? (Use a fresh one as it may expire too quickly)"
      private: yes

  tasks:
    - name: template out steamcmd script
      template:
        src: ./templates/install-script.txt.j2
        dest: "{{ install_script }}"
        owner: "{{ steam_user.name }}"
        mode: 0600

    - name: install Starbound server with steamcmd
      block:
        - name: run install script
          command: /usr/games/steamcmd +runscript "{{ install_script }}"
          args:
            creates: "{{ server_install_dir }}/linux/starbound_server"
          become_user: "{{ steam_user.name }}"
      always:
        - file:
            path: "{{ install_script }}"
            state: absent

    - name: create Starbound server config directory
      file:
        path: "{{ server_install_dir }}/storage"
        state: directory
        owner: "{{ steam_user.name }}"

    - name: template Starbound server config
      template:
        src: ./templates/starbound_server.config.j2
        dest: "{{ server_install_dir }}/storage/starbound_server.config"
        owner: "{{ steam_user.name }}"

    - name: template systemd service unit
      template:
        src: ./templates/starbound-server.service.j2
        dest: /etc/systemd/system/starbound-server.service
        owner: "{{ steam_user.name }}"
        mode: 0600

    - name: start Starbound server service
      systemd:
        name: starbound-server
        enabled: yes
        daemon_reload: yes
        state: started